language: python
python: 3.6
env:
  global:
  - PKG_NAME=bgen_reader
  - CIBW_SKIP="cp27-* cp34-* cp35-* *i686*"
  - CIBW_BEFORE_BUILD_LINUX=ci/before-build-linux
  - CIBW_BEFORE_BUILD_MACOS=ci/before-build-macos
  - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
  - URL=https://raw.githubusercontent.com/horta/ci/master
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install --upgrade pip
        - pip3 install --upgrade virtualenv
        - virtualenv $HOME/venv # virtualenv will use Python 3
        - source $HOME/venv/bin/activate
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
    - cmake
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/almosthere/master/install)
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/bgen/master/install)
- bash <(curl -fsSL $URL/travis-check-readme.sh)
- bash <(curl -fsSL $URL/travis-py-min-deps.sh)
- bash <(curl -fsSL $URL/travis-py-check-style.sh)
- bash <(curl -fsSL $URL/travis-py-check-black.sh)
- bash <(curl -fsSL $URL/travis-py-dev-test.sh)
- bash <(curl -fsSL $URL/travis-py-install-test.sh)
- bash <(curl -fsSL $URL/travis-py-doctest.sh)
script:
- bash <(curl -fsSL $URL/travis-py-sdist-test.sh)
- git clean -xdf
- python -m pip install cibuildwheel>=0.12.0
- cibuildwheel --output-dir wheelhouse
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: FQibXjKOCq3lzPn9QLTZ0GMZXOkq3A35G8PSLrbFjOtd7BlkX0nJ9kuMg4NMP2OaAVirv3L4Kd8cceWifx1F/LAn1u+ABiVfMrM4xV3rA8xHL8Yr4zyesEPsDXoZBAymJPBd3RMeib3sCjtPQl2o9reUeycTyTAwDC010PnR29rTH6WLutpS8WcjKMxkfh2+h6Ks85o6DWLu+sVRnrxZq/y+xdbwHzZiSUwjGA8rF88Iw/EBfFNDR9DDiQyYY+dmvi7efoYPol07ZRVAmKdxK9TXPlye/x+M0mu9jeMyxhdUQc1x4YhK5CXJEI3R1bo8yEpKCskCOVpYOxkbOeDM1cu3rptROhbzQs+02j4Moqk5vC+4Gl6NwuB2fbnzijWpq17Kg5oQppMBMP8f7y85ws75owMFdYGdw49tR2pyL8BYsIqxBFq/SYhYwuZ7wnGNgKN4DKxwc+lRv/zICAipt04tMQsyPXq071wjZt44gZgoJ3rYbfbYNShDQOI+nbKhwHRV5/PmkBDT/KD3KVapjmT1q2wY7gGN8/2dIrPjmqveBgKho3QAmc0UV8SBVLw4rZxGJRGzRR6y58sCd0ynzB0tggUksrGO/gT1QnzgABPQ2Of137HfDEXXaSKdc4HCw9W0D0gltLaHV5b8iU4gQf1VsAt/I9mmp5Thrtvf9cc=
  on:
    tags: true
    repo: limix/bgen-reader-py
    branch: master
